/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Onlineexam;

import java.lang.reflect.Array;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author SRI VYSHNAVI
 */

public class writeTest extends javax.swing.JFrame {

    /**
     * Creates new form writeTest
     */
    public Connection con;
    String username,s,tname;
    public writeTest(String testname,String user) {
        initComponents();
        this.setLocationRelativeTo(null);
         username=user;
        
        tname=testname;
        head.setText(username+" "+tname);
        
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/onlineexam";
                String name1 = "root";
                String pass = "";
                String q1, q2, q3, q4, q5;
                con = DriverManager.getConnection(url, name1, pass);
                String msg="",s="select * From questions Where testname='"+tname+"'";
                PreparedStatement ps = con.prepareStatement(s);
                 ResultSet rset = ps.executeQuery();
                while (rset.next()) {
               
                q1 = rset.getString("question1");
                q2 = rset.getString("question2");
                q3 = rset.getString("question3");
                q4 = rset.getString("question4");
                q5 = rset.getString("question5");
                
            
                qu1.setText(q1);
                qu2.setText(q2);
                qu3.setText(q3);
                qu4.setText(q4);
                qu5.setText(q5);
                }
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(rootPane,"error");
        }
                
      
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        qu1 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        qu2 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        qu3 = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        qu4 = new javax.swing.JLabel();
        a5 = new javax.swing.JTextField();
        qu5 = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        head = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qu1.setText("Question-1:");
        getContentPane().add(qu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1030, 32));
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, 40));

        qu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qu2.setText("Question-2:");
        getContentPane().add(qu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 950, 30));
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 130, 40));

        qu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qu3.setText("Question-3:");
        getContentPane().add(qu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 940, 30));
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 130, 40));

        qu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qu4.setText("Question-4:");
        getContentPane().add(qu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 950, 30));
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 140, 40));

        qu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qu5.setText("Question-5:");
        getContentPane().add(qu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 940, 40));
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 130, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, -1, -1));

        head.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("Exam Name");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 10, 1040, -1));

        jLabel1.setText("Answer:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        try {
           String ans1, ans2, ans3, ans4, ans5;
            String msg="",s="select * From questions Where testname='"+tname+"'";
            String an1 = a1.getText();
            String an2 = a2.getText();
            String an3 = a3.getText();
            String an4 = a4.getText();
            String an5 = a5.getText();
            int rt=0;
            int wrong=0;
            PreparedStatement ps = con.prepareStatement(s);
            ResultSet rset = ps.executeQuery();
            while (rset.next()) {
               
                ans1 = rset.getString("ans1");
                ans2 = rset.getString("ans2");
                ans3 = rset.getString("ans3");
                ans4 = rset.getString("ans4");
                ans5 = rset.getString("ans5");
                

                String arr1[] = new String[]{ans1,ans2,ans3,ans4,ans5};
                String arr2[] =new String[]{an1,an2,an3,an4,an5};
                for (int i = 0; i < 5; i++) {
                    if (arr1[i].equals(arr2[i])) {
                        rt+=10;
                    }
                    else{
                       wrong+=1;
                    }
                }
                
               
                String res=String.valueOf(rt);
                dispose();
                new Results(res,username,tname).setVisible(true);
            }

                          }
                      
                          

                          catch(Exception e){
                                JOptionPane.showMessageDialog(rootPane,"error");  
                                  }
                          
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(writeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(writeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(writeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(writeTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new writeTest("english","Admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel qu1;
    private javax.swing.JLabel qu2;
    private javax.swing.JLabel qu3;
    private javax.swing.JLabel qu4;
    private javax.swing.JLabel qu5;
    // End of variables declaration                   
}
